name: ESP32 Firmware Update

on:
  push:
    branches: [ main ]

jobs:
  firmware_update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build firmware
      run: |
        pio run -e esp32doit-devkit-v1

    - name: Generate OTA firmware image
      run: |
        pio run -t buildfs -e esp32dev
        pio run -t upload --upload-port https://ee66-102-88-63-49.ngrok-free.app -e esp32dev

    - name: Download Firmware
      run: |
        wget https://ee66-102-88-63-49.ngrok-free.app/firmware/firmware.bin -O firmware.bin

    # Additional steps if needed, such as testing firmware
