name: ESP32 Firmware Update

on:
  push:
    branches: [ main ]

jobs:
  firmware_update:
    runs-on: ubuntu-latest

    steps:
    - name: Install PlatformIO
      run: |
        sudo apt-get update
        sudo apt-get install python3-pip
        pip3 install platformio 
  
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build firmware
      run: |
        pio run -e esp32doit-devkit-v1

    - name: Generate OTA firmware image
      run: |
        pio run -t buildfs -e esp32doit-devkit-v1

    - name: Upload Firmware to NGrok Server
      run: |
        curl -X POST -F "file=@.pio/build/esp32doit-devkit-v1/spiffs.bin" https://ee66-102-88-63-49.ngrok-free.app/upload

    # Additional steps if needed, such as testing firmware
